[package]
name = "wuzi"
version = "0.1.0"
authors = ["Yun Li <one.awesome.peanut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = {version = "0.8.0", features=["net", "os-poll"]}
